config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'courses#index'
 
  resources :groups do
  	resources :students
  end
  resources :teachers, :courses, :users, :groups, :students
end

app/models/student.rb
class Student < ApplicationRecord
	validates :name, presence: true

	belongs_to :group
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	#before_filter :check_if_admin, only: [:edit, :update, :new, :create, :destroy]
	def index
		@students = Student.all
	end

	def show
		unless @student = Student.where(id: params[:id]).first
			render "students/show"
			render "public/404.html"
		end
	end

	def edit
		@student = Student.find(params[:id])
	end

	def update
		@student = Student.find(params[:id])
		@student.update_attributes(student_params)
		if @student.errors.empty?
			redirect_to student_path(@student)
		else
			render "edit"
		end
	end
	
	def new
		@student = Student.new
	end
	
	def create
		@student = Student.new(student_params)
		@student.save
		if @student.errors.empty?
			redirect_to students_path(@student)
		else
			render "new"
		end
	end

	def destroy
		@student = Student.find(params[:id])
		@student.destroy
		redirect_to action: "index"
	end

	private
	def student_params
		params.require(:student).permit(:name, :birth_date, :school_name, :address, :passport_data, :phone_number, :group_id)
	end

	#def check_if_admin
	#	render file: "public/403.html", status: 403 unless params[:admin]
	#end

end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/edit.html.haml
%h1 Редактирование студента
= form_for @student do |f|
  %p
    Имя
    %br/
    = f.text_field :name
  %p
    Дата рождения
    %br/
    = f.text_field :birth_date
  %p
    Учебное заведение
    %br/
    = f.text_field :school_name
  %p
    Адрес
    %br/
    = f.text_field :address
  %p
    Паспортные данные
    %br/
    = f.text_field :passport_data
  %p
    Номер телефона
    %br/
    = f.text_field :phone_number
  %p
    Учебная группа
    %br/
    = f.text_field :group_id
  %p
    = f.submit "Применить изменения"

app/views/students/index.html.haml
- if user_signed_in? || admin_signed_in?
  %h1 Cтуденты
  - if admin_signed_in?
    .buttons
      %button.btn.btn-default{:type => "button"}
        %h5= link_to "Добавить", "students/new"
- if @students.empty?
  %b Нет студентов
- else
  - if user_signed_in? || admin_signed_in?
    %table.table.table-striped
      %tr
        %th
        %th Имя
        %th Дата рождения
        %th Название учебного заведения
        %th Адрес
        %th Паспортные данные
        %th Номер телефона
        %th Учебная группа
        %th
        %th
      - @students.each do |s|
        %tr
          %td= link_to s.id, student_path(s)
          %td= link_to s.name, student_path(s)
          %td= link_to s.birth_date, student_path(s)
          %td= link_to s.school_name, student_path(s)
          %td= link_to s.address, student_path(s)
          %td= link_to s.passport_data, student_path(s)
          %td= link_to s.phone_number, student_path(s)
          %td= link_to s.group.name, group_path(s)
          - if admin_signed_in?
            %td
              = link_to edit_student_path(s) do
                %i.glyphicon.glyphicon-edit
            %td
              = link_to s, method: :delete, data: {confirm: "Точно удалить?"} do
                %i.glyphicon.glyphicon-remove
    - if user_signed_in? || admin_signed_in?
      .buttons
        %button.btn.btn-basic{:type => "button"}
          = link_to "Преподаватели" , teachers_path
          \&amp;nbsp
        %button.btn.btn-basic{:type => "button"}
          = link_to "Курсы", courses_path
          \&amp;nbsp
        %button.btn.btn-basic{:type => "button"}
          = link_to "Группы",   groups_path

app/views/students/new.html.haml
%h1 Создать нового студента
= form_for Student.new do |f|
  %p
    Имя
    %br/
    = f.text_field :name
  %p
    Дата рождения
    %br/
    = f.text_field :birth_date
  %p
    Учебное заведение
    %br/
    = f.text_field :school_name
  %p
    Адрес
    %br/
    = f.text_field :address
  %p
    Паспортные данные
    %br/
    = f.text_field :passport_data
  %p
    Номер телефона
    %br/
    = f.text_field :phone_number
  %p
    Учебная группа
    %br/
    = f.text_field :group_id
  %p
    = f.submit "Cоздать"

app/views/students/show.html.haml
%h1 Информация о студенте
%ul
  %li
    ID: #{@student.id}
  %li
    Имя: #{@student.name}
  %li
    Дата рождения: #{@student.birth_date}
  %li
    Учебное заведение: #{@student.school_name}
  %li
    Адрес: #{@student.address}
  %li
    Паспортные данные: #{@student.passport_data}
  %li
    Номер телефона: #{@student.phone_number}
  %li
    Учебная группа: #{@student.group.name}
.buttons
  %button.btn.btn-basic{:type => "button"}
    = link_to "Назад", students_path