config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'courses#index'
 
  resources :groups do
  	resources :students
  end
  resources :teachers, :courses, :users, :groups, :students
end

app/models/group.rb
class Group < ApplicationRecord
	validates :name, presence: true

	has_many   :students
	belongs_to :course
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
	#before_filter :check_if_admin, only: [:edit, :update, :new, :create, :destroy]
	def index
		@groups = Group.all
	end

	def show
		unless @group = Group.where(id: params[:id]).first
			render "groups/show"
			render "public/404.html"
		end
	end

	def edit
		@group = Group.find(params[:id])
	end

	def update
		@group = Group.find(params[:id])
		@group.update_attributes(group_params)
		if @group.errors.empty?
			redirect_to group_path(@group)
		else
			render "edit"
		end
	end
	
	def new
		@group = Group.new
	end
	
	def create
		@group = Group.new(group_params)
		@group.save
		if @group.errors.empty?
			redirect_to groups_path(@group)
		else
			render "new"
		end
	end

	def destroy
		@group = Group.find(params[:id])
		@group.destroy
		redirect_to action: "index"
	end

	private
	def group_params
		params.require(:group).permit(:name, :course_id)
	end

	#def check_if_admin
	#	render file: "public/403.html", status: 403 unless params[:admin]
	#end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/edit.html.erb
<h1>Редактирование учебной группы</h1>

<%= form_for @group do |f| %>

	<p> Название учебной группы <br/> <%= f.text_field :name %> </p>
	<p> Учебный курс <br/> <%= f.text_field :course_id %> </p>

	<p> <%= f.submit "Применить изменения" %> </p>

<% end %>

app/views/groups/index.html.erb
<% if user_signed_in? || admin_signed_in? %>
<h1>Учебные группы</h1>

<% if admin_signed_in? %>
	<div class="buttons">
		<button type="button" class="btn btn-default">
			<h5><%=link_to "Добавить", "groups/new" %></h5>
		</button>
	</div>
<% end %>
<% end %>

<% if @groups.empty? %>
	<b>Нет учебных групп</b>
<% else %>

<% if user_signed_in? || admin_signed_in? %>
	<table class="table table-striped">
			<tr>
				<th></th>
				<th>Учебная группа</th>
				<th>Учебный курс</th>
				<th>Студент группы</th>
				<th></th>
				<th></th>
			</tr>
		<% @groups.each do |g| %>
			<tr>
				<td><%=link_to g.id, group_path(g)%></td>
				<td><%=link_to g.name, group_path(g)%></td>
				<td><%=link_to g.course.name, course_path(g)%></td>
				<% g.students.each do |student| %>
					<td><%=link_to student.name, student_path(g)%></td>
				<% end %>
				<% if admin_signed_in? %>
				<td><%=link_to edit_group_path(g) do%>	
						<i class="glyphicon glyphicon-edit"></i>		
					<% end %>
				</td>
				<td><%=link_to g, method: :delete, data: {confirm: "Точно удалить?"} do%>
						<i class="glyphicon glyphicon-remove"></i>
					<% end %>
				</td>
				<% end %>
			</tr>
		<% end %>
<% end %>
<% end %>
	</table>
	
</br>
<% if user_signed_in? || admin_signed_in? %>
<div class="buttons">
<button type="button" class="btn btn-basic">
	<%= link_to "Курсы", courses_path %> &nbsp
</button>  
<button type="button" class="btn btn-basic">
	<%= link_to "Преподаватели", teachers_path %> &nbsp
</button>
<button type="button" class="btn btn-basic">
	<%= link_to "Студенты", students_path %>
</button>
</div>
<% end %>

app/views/groups/new.html.erb
<h1>Создать новую группу</h1>

<%= form_for Group.new do |f| %>

	<p> Название группы <br/> <%= f.text_field :name %> </p>
	<p> Учебный курс <br/> <%= f.text_field :course_id %> </p>

	<p> <%= f.submit "Cоздать" %> </p>

<% end %>

app/views/groups/show.html.erb
<h1>Информация об учебной группе</h1>

<ul>
	<li>ID: <%=@group.id%></li> 
	<li>Название группы: <%=@group.name%> </li>
	<li>Название курса: <%=@group.course.name%>  </li>	
</ul>

<div class="buttons">
<button type="button" class="btn btn-basic">
	<%=link_to "Назад", groups_path%>
</button>
</div>