config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'courses#index'
 
  resources :groups do
  	resources :students
  end
  resources :teachers, :courses, :users, :groups, :students
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ROLES = %i[admin author]

  def roles=(roles)
  	#roles= [*roles].map { |r| r.to_sym }
  	self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r) }.inject(0, :+)
  end

  def roles
  	ROLES.reject do |r|
  		((roles_mask.to_i || 0) & 2**ROLES.index(r)).zero?
  	end
  end

  def has_role?(role)
  	roles.include?(role.to_s)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
		unless @user = User.where(id: params[:id]).first
			render "users/show"
			render "public/404.html"
		end
	end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Добро пожаловать!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def index
  	@users = User.all
  end

  def update
		@user = User.find(params[:id])
		@user.update_attributes(user_params)
		if @user.errors.empty?
			redirect_to user_path(@user)
		else
			render "edit"
		end
	end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>Обновить профиль</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Сохранить изменения", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<h1>Все пользователи</h1>

<ul class="users">
  <% @users.each do |user| %>
    <table class="table-striped">
    	<tr>
    		<th>ID</th>
    		<th>Email</th>
    	</tr>
    	<tr>
    		<td><%= link_to user.id, users_path%></td>
      		<td><%= link_to user.email, users_path %></td>
    	</tr>
    </table>
  <% end %>
</ul>

</br>
<% if admin_signed_in? %>
<div class = button>
	<button type="button" class= "btn btn-basic">
		<%=link_to "Преподаватели" , teachers_path%> 
		&nbsp
	</button>
	
	<button type="button" class= "btn btn-basic">
		<%=link_to "Студенты", students_path%> &nbsp
	</button>

	<button type="button" class= "btn btn-basic">
		<%=link_to "Группы", groups_path%>
	</button>

	<button type="button" class= "btn btn-basic">
		<%=link_to "Курсы", courses_path%>
	</button>
</div>
<% end %>

app/views/users/new.html.erb
<h1>Новый пользователь</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= simple_form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      

      <%= f.label :email %>
      

      <%= f.label :password %>
      

      <%= f.label :password_confirmation, "Confirmation" %>
      

      <%= f.submit "Создать", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1>Информация о пользователе</h1>

<ul class="user">
  <% @user.each do |user| %>
    <li>
      Имя: <%=link_to user.name, user_path %>
      Email: <%=link_to user.email, user_path %>
    </li>
  <% end %>
</ul>

<div class="button">
	<button type="button class="btn btn-basic">
		<%=link_to "Назад", users_path%>
	</button>
</div>