config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'courses#index'
 
  resources :groups do
  	resources :students
  end
  resources :teachers, :courses, :users, :groups, :students
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
	#before_action :check_if_admin, only: [:edit, :update, :new, :create, :destroy]
	def index
		@courses = Course.all
	end

	def show
		unless @course = Course.where(id: params[:id]).first
			render "courses/show"
			render "public/404.html"
		end
	end

	def edit
		@course = Course.find(params[:id])
	end

	def update
		@course = Course.find(params[:id])
		@course.update_attributes(course_params)
		if @course.errors.empty?
			redirect_to course_path(@course)
		else
			render "edit"
		end
	end
	
	def new
		@course = Course.new
	end
	
	def create
		@course = Course.new(course_params)
		@course.save
		if @course.errors.empty?
			redirect_to courses_path(@course)
		else
			render "new"
		end
	end

	def destroy
		@course = Course.find(params[:id])
		@course.destroy
		redirect_to action: "index"
	end
	
	private
	def course_params
		params.require(:course).permit(:name, :group_id)
	end

	#def check_if_admin
	#	render file: "public/403.html", status: 403 unless params[:author]
	#end

end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/edit.html.haml
%h1 Редактирование учебного курса
= form_for @course do |f|
  %p
    Название курса
    %br/
    = f.text_field :name
  %p
    = f.submit "Применить изменения"

app/views/courses/index.html.haml
- if user_signed_in? || admin_signed_in?
  %h1 Курсы дополнительного образования
  - if admin_signed_in?
    .button
      %button.btn.btn-default{:type => "button"}
        %h5= link_to "Добавить", "courses/new"
- if @courses.empty?
  %b Нет курсов
- else
  - if user_signed_in? || admin_signed_in?
    %table.table.table-striped
      %tr
        %th
        %th Название курса
        %th Учебная группа
        %th Преподаватель курса
        %th
        %th
      - @courses.each do |c|
        %tr
          %td= link_to c.id, course_path(c)
          %td= link_to c.name, course_path(c)
          %td= link_to c.group.name, group_path(c)
          %td= link_to c.teacher.name, teacher_path(c)
          - if admin_signed_in?
            %td
              = link_to edit_course_path(c) do
                %i.glyphicon.glyphicon-edit
            %td
              = link_to c, method: :delete, data: {confirm: "Точно удалить?"} do
                %i.glyphicon.glyphicon-remove
    - if user_signed_in? || admin_signed_in?
      .button
        %button.btn.btn-basic{:type => "button"}
          = link_to "Преподаватели" , teachers_path
          \&amp;nbsp
        %button.btn.btn-basic{:type => "button"}
          = link_to "Студенты", students_path
          \&amp;nbsp
        %button.btn.btn-basic{:type => "button"}
          = link_to "Группы", groups_path

app/views/courses/new.html.haml
%h1 Создать новый курс
= form_for Course.new do |f|
  %p
    Название курса
    %br/
    = f.text_field :name
  %p
    = f.submit "Cоздать"

app/views/courses/show.html.erb
<h1>Информация о курсе</h1>

<ul>	
	<li>ID: <%=@course.id%> </li> 
	<li>Название курса: <%=@course.name%> </li>
</ul>

<div class="button">
	<button type="button class="btn btn-basic">
		<%=link_to "Назад", courses_path%>
	</button>
</div>